/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'matteo' at '15/05/16 11:15' with Gradle 2.13
 *
 * @author matteo, @date 15/05/16 11:15
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
