/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'matteo' at '15/05/16 11:15' with Gradle 2.13
 *
 * @author matteo, @date 15/05/16 11:15
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
